development:
  adapter: postgresql
  encoding: utf8
  database: ece2019_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ece2019_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ece2019_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST